import type { Metadata } from "next";
import { Lora, Geist_Mono, Fraunces, Inter } from "next/font/google";
import { TooltipProvider } from "@/frontend/components/ui/tooltip";
import "@/frontend/styles/globals.css";

// Body/UI copy runs on an old-fashioned text serif, not a geometric sans —
// this is mapped to the app's default `--font-sans`/`font-sans` token, so
// every button, label, nav item, and paragraph that doesn't explicitly ask
// for --font-display or mono inherits it automatically. A sans-serif
// interface font (Geist, Inter, etc.) is one of the most immediate
// "generated by an AI tool" signals; a text serif throughout is what keeps
// this reading like a printed ledger instead of a SaaS dashboard.
const bodySerif = Lora({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// A warm, editorial variable serif with organic terminals, reserved for
// large display headlines/titles — deliberately not a script/cursive face,
// and deliberately a different serif from the body copy so headlines still
// read as a distinct, higher-contrast voice rather than one flat typeface
// used for everything.
const displaySerif = Fraunces({
  variable: "--font-display",
  subsets: ["latin"],
  axes: ["opsz", "SOFT", "WONK"],
});

// Inter is loaded for the remix landing page which references 'Inter', sans-serif
// in its CSS. Using next/font avoids a CSS @import that would break PostCSS ordering.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "dietre — When2meet for catering",
  description:
    "Anonymous, ingredient-level dietary matching for hosts running events of 30–300+ people. Demo city: Blacksburg / Virginia Tech.",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${bodySerif.variable} ${geistMono.variable} ${displaySerif.variable} ${inter.variable} antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
